---
### Common settings
openshift_logging_elasticsearch_image_pull_secret: "{{ openshift_logging_image_pull_secret }}"
openshift_logging_elasticsearch_namespace: openshift-logging

openshift_logging_tribe_nodeselector: "{{ openshift_logging_es_nodeselector | default('') }}"
openshift_logging_tribe_cpu_limit: null
openshift_logging_tribe_cpu_request: "{{ openshift_logging_es_cpu_request | default('300m') }}"
openshift_logging_tribe_memory_limit: "{{ openshift_logging_es_memory_limit | default('2i') }}"

# ES deployment type
openshift_logging_tribe_deployment_type: "client"

# ES deployment name
openshift_logging_tribe_deployment_name: ""

# One of ['emptydir', 'pvc', 'hostmount']
openshift_logging_tribe_storage_type: "emptydir"

# hostmount options
openshift_logging_tribe_hostmount_path: ""
openshift_logging_tribe_hostmount_nodeselector_key: "logging-es-tribe"

openshift_logging_elasticsearch_proxy_cpu_request: "100m"
openshift_logging_elasticsearch_proxy_memory_limit: "64Mi"
openshift_logging_elasticsearch_prometheus_sa: "system:serviceaccount:{{openshift_prometheus_namespace | default('openshift-metrics')}}:prometheus"

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_logging_elasticsearch_ops_deployment: false

openshift_logging_elasticsearch_ops_allow_cluster_reader: false

# openshift_logging_es_config is a hash to be merged into the defaults for the elasticsearch.yaml
openshift_logging_es_config: {}


openshift_logging_master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
openshift_logging_master_public_url: "{{ 'https://' + openshift.common.public_hostname + ':' ~ openshift_master_api_port }}"
openshift_logging_es_host: logging-es
openshift_logging_es_port: 9200
openshift_logging_es_ca: /etc/fluent/keys/ca
openshift_logging_es_client_cert: /etc/fluent/keys/cert
openshift_logging_es_client_key: /etc/fluent/keys/key
